import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const interFont = localFont({
  src: "./fonts/Inter-VariableFont_wght.ttf",
  variable: "--font-inter",
  weight: "100 900",
});

const montserratFont = localFont({
  src: "./fonts/Montserrat-VariableFont_wght.ttf",
  variable: "--font-montserrat",
  weight: "100 900",
});

export const montserratFontLogo = localFont({
  src: "./fonts/Montserrat-VariableFont_wght.ttf",
  variable: "--font-montserrat-for-logo",
  weight: "900",
});

export const metadata: Metadata = {
  title: "Spend Wise",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${interFont.variable} ${montserratFont.variable} ${montserratFontLogo.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
